### ISSUE TITLE
use of ACT for testing github action

### ISSUE THREAD

**Issue by gilliM** [swisstopo/topo-satromo#10]
I've used the ACT software to check the github action behavior locally. https://github.com/nektos/act

`act -j build -W .github/workflows/run-processor.yml -s GOOGLE_CLIENT_SECRET="$(< secrets/geetest-credentials.secret)"`

[act_example.txt](https://github.com/swisstopo/topo-satromo/files/12548083/act_example.txt)

With this setup, the run is recognized as being in production.
We should setup another way to determine if we are on prod or dev if we want to use this tool for example.

**Comment by davidoesch** [comment]
nice, need to demo this more this facilitates the dev process
