### ISSUE TITLE
No int16 step0_processor_s2_sr for registrationv alues

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#21]
is there a reason why  step0_processor_s2_sr  compared to step0_processor_s2_toa  does not get  casted to int16?
see https://github.com/swisstopo/topo-satromo/blob/3536f4307ada36ed251383ddb3b70be28273b054/step0_processors/step0_processor_s2_sr.py#L425C9-L429C51

**Comment by gilliM** [comment]
good catch.
I was focusing on the band export, that don't need an explicit cast for SR (while an explicit cast is needed for TOA). I will correct that.

**Comment by gilliM** [comment]
btw what do you think about casting reg_confidence to uint8 ?

**Comment by davidoesch** [comment]
correction for reg x, reg y makes sense, I close it
