### ISSUE TITLE
 if 'cleaning_older_than' in config.step0[collection]: error

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#22]
Steps to reproduce

-created empty  asset collection  https://code.earthengine.google.com/?asset=projects/geetest-386915/assets/col_s2_sr  

then
- running python satromo_processor.py 
( this configuration: https://github.com/swisstopo/topo-satromo/blob/step0/configuration/dev_config.py  on this commithttps://github.com/swisstopo/topo-satromo/commit/5891bce2dcba44ea233164661e176fe6200f85a4 )

I get 
                'projects/geetest-386915/assets/col_s2_sr'
                  File "C:\temp\topo-satromo\step0_functions.py", line 29, in step0_check_collection
                    if 'cleaning_older_than' in config.step0[collection]:
                                                ~~~~~~~~~~~~^^^^^^^^^^^^
                  File "C:\temp\topo-satromo\step0_functions.py", line 16, in step0_main
                    ok = step0_check_collection(step0_collection, temporal_coverage, current_date_str)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  File "C:\temp\topo-satromo\satromo_processor.py", line 841, in <module>
                    collections_ready_for_processors = step0_main(
                                                       ^^^^^^^^^^^
                KeyError: 'projects/geetest-386915/assets/col_s2_sr'

I assume that import configuration does not work:" import "configuration" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)"

-> why?

**Comment by gilliM** [comment]
you need to adapt the collection name in the step0 configuration (https://github.com/swisstopo/topo-satromo/blob/5891bce2dcba44ea233164661e176fe6200f85a4/configuration/dev_config.py#L96)

**Comment by davidoesch** [comment]
thanks,
