### ISSUE TITLE
L2A_ exports have masked clouds 

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#24]
**Steps to reproduce**

"product_name": "S2_LEVEL_2A",
in satromo_processor.py
set current_date_str = "2023-06-13"

Then run script

**Result:**

Exported  L2A image  has  0 values for clouds  ( Lake thun)
![image](https://github.com/swisstopo/topo-satromo/assets/4577727/e9f8f560-d297-45b6-b21b-e7b76195149f)

**Expected Result:**

Clouds are not masked in RAW Data

**Comment by gilliM** [comment]
https://github.com/swisstopo/topo-satromo/pull/32

**Comment by davidoesch** [comment]
fixed with https://github.com/swisstopo/topo-satromo/pull/32
