### ISSUE TITLE
CloudScore+ evaluate as alternative

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#25]
**Is your feature request related to a problem? Please describe.**
s2cloudless Cloud mask can be a struggle

**Describe the solution you'd like**
[CloudScore+](https://medium.com/google-earth/all-clear-with-cloud-score-bd6ee2e2235e) als [GEE Asset](https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_CLOUD_SCORE_PLUS_V1_S2_HARMONIZED): New cloud options , to be evlauated

Find first the appropriate thresholds, then replacve in the step0 s2cloudless if we have better results

**Comment by HendrikWulf** [comment]
I compared S2cloudless and Cloud Score Plus. I am quite impressed about cloud score plus. It visually outscores S2cloudless almost every time. Feel free to convince yourself by scrolling through some months: https://code.earthengine.google.com/4738343799bef9d82b6f46fd72e0c4cc

If you agree, I would propose to replace S2cloudless with cloud score plus for S2_toa and S2_sr.

**Comment by Tschoun** [comment]
I've also tested the results by both algorithms and am favouring CS+ too. 

- One concern was, that it might pick up on other changes, that we would like to show, but I've not yet seen any evidence of such a case. 
- Another argument occasionally mentioned concerning CS+ was that the hype comes from its impressive F1 score in [Pasquarella et al. (2023)](https://openaccess.thecvf.com/content/CVPR2023W/EarthVision/papers/Pasquarella_Comprehensive_Quality_Assessment_of_Optical_Satellite_Imagery_Using_Weakly_Supervised_CVPRW_2023_paper.pdf) whereas it is outperformed in precision and recall by other algorithms. Nevertheless, in a direct comparison CS+ performs better in these two accuracy metrics as well compared to s2cloudless.

I therefore fully agree, replacing s2cloudless with CS+ for TOA and SR is the way forward.

**Comment by Tschoun** [comment]
So far I've had visually good results with a CS+ threshold of gte 0.70 but this was experimental and not systematically tested.

**Comment by Tschoun** [comment]
@HendrikWulf - I will add the option of CS+ to the Sentinel-2 scripts. I'm planning on making it the default, but giving the possibility in the code to choose between CS+ and s2cloudless. Thanks for your comparison.
