### ISSUE TITLE
assets: reg_confidence to 8bit

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#31]
**Is your feature request related to a problem? Please describe.**
reg_confidence in assets is curretnly in float and uses up quite some disk spaces. Converting to 8bit would reducs the data store .

**Describe the solution you'd like**
check if  values 0 to 99 make sense @gilliM 
change code to cast

- [x]  https://github.com/swisstopo/topo-satromo/blob/c31c5cd3866685fc7ae3c2adbf335c02b41f3544/step0_processors/step0_processor_s2_sr.py#L430
- [x] https://github.com/swisstopo/topo-satromo/blob/c31c5cd3866685fc7ae3c2adbf335c02b41f3544/step0_processors/step0_processor_s2_toa.py#L455
to 16bit while ensuring it does not have impact on the registration process (Int8 is not a solution since COGTiff is not supported)

**Describe alternatives you've considered**
 multiply reg_confidence  with 1000  cast to int8 for storing to assets

**Comment by gilliM** [comment]
I'm implementing a cast to UInt8 (Btw don't you do a confusion between bytes/Uint8 vs int8 ? or maybe the confusion is on my side.)

**Comment by davidoesch** [comment]
Uint8 vs int8: confusion probably on my side

Asset in uint8
Exports int16 (since cog is not supporting Int8)

**Comment by gilliM** [comment]
https://github.com/swisstopo/topo-satromo/pull/32

**Comment by gilliM** [comment]
> Uint8 vs int8: confusion probably on my side
> 
> Asset in uint8 Exports int16 (since cog is not supporting Int8)

I'm pretty sure cog tiff support UInt8 (maybe under the names Bytes).

**Comment by davidoesch** [comment]
@gilliM "According to https://gdal.org/drivers/raster/gtiff.html no support for Int8 for Gtiff / CloudGeotiff"

**Comment by gilliM** [comment]
UInt8 are names here "Byte", first on the list. It stores integer values between 0 to 255.
Int8 on another hand is a uncommon type, containing signed bytes, with integer values between usually -128 to 127.
As for example the registration confidence is always positive, it's logically ok to store in as integer between 0 to 100, so in Byte format.

**Comment by davidoesch** [comment]
yep makes sense. side note:  I initially wanted to store the NDVI values  casted to signedbyte/int8.  stored in uint8 I would need to cast it and  add 100 to fit the -100 to +100 into 0-200  range. Which is to cumbersome for the users
