### ISSUE TITLE
aoi_image needed?

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#33]
in 
py: https://github.com/swisstopo/topo-satromo/blob/3410a6cefc87da73c088146e49f08ef9b118b156/step0_processors/step0_processor_s2_sr.py#L384 
JS:
https://code.earthengine.google.com/a08635b7f3c83b082c35023a72743ec4  line 437
we have for the registration process

# extract the mosaic geometry
        aoi_image = imageOrig.geometry()

-> is this needed, can't see the usage of this variable. 

Can I delete it?

**Comment by HendrikWulf** [comment]
Good point. It was a remnant of a previous script and can be deleted. Done in the JS repository.

**Comment by davidoesch** [comment]
fixed
