### ISSUE TITLE
Shadow non binary Mask  missing values

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#34]
**Describe the bug**
the cloud mask is not binray, there is a third values

**To Reproduce**
1. Go to (https://code.earthengine.google.com/f20bc8f8c25a96e9db70e7dc91f1345e)
2. run 
3. Zoom to Eigernordwand , shadow mask layer
4. See missing binary mask

**Expected behavior**
Area should be masked for the eigernordwand

**Screenshots**
![image](https://github.com/swisstopo/topo-satromo/assets/4577727/f5a640d6-2836-46ec-94aa-7712b13446f1)

**OS, python version**
 - GEE JS

**Comment by HendrikWulf** [comment]
Good observation. 
The terrain mask was also masked based on by the cloudAndCloudShadowMask. This bug derived from the "darkPixels" variable defined in the addTerrainShadow function (line 223). The bands used here ['B8','B11','B12'] had already been cloud-and-cloud-shadow-masked. Therefore, they introduced this mask into the terrainShadow-mask.
var darkPixels = image.select(['B8','B11','B12']).reduce(ee.Reducer.sum()).lt(2500);

To fix this unwanted behavior, we add the unmasked "darkPixels" variable as a Band defined in the maskCloudsAndShadows and reuse it in the addTerrainShadow function.
https://code.earthengine.google.com/d214554fb8cdde5880e47cde5e204144

The JS code of S2-toa and Landsat is updated in the Deliverables repository.

**Comment by davidoesch** [comment]
thanks tested it and added it as well in the NPOACCESS accoutn https://code.earthengine.google.com/d017c023cda8ee526a38b03155750b91

@gilliM  can you make the changes in the sr and toa scripts?

**Comment by gilliM** [comment]
Correction ongoing https://github.com/gilliM/topo-satromo/commit/8a08b88733d3265f9a5aff8ba7ad096119f864a2
But i need to clarify how this impact the S2 SR script to go forward.

**Comment by gilliM** [comment]
S2 SR clarified: no change needed as topographic correction is already applied on the data, which imply that we cannot detect dark pixel as we do for TOA.
