### ISSUE TITLE
export 20m and 10m PRODUCT_S2_LEVEL_2A and PRODUCT_S2_LEVEL_1C 

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#35]
**Describe the bug**
PRODUCT_S2_LEVEL_1C   and PRODUCT_S2_LEVEL_2A have 10m and  20m Bands. 
Export to assets works (see projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS) as defined in dev_config.py seems to work
They are now available as private collction

Now the export to drive process is needs to be redefined , since we have a collection with 2 items per day : 20m and 10m bands 
the first image https://github.com/swisstopo/topo-satromo/blob/011d4356d3fa2f7753cef38fa4968e6c92559601/satromo_processor.py#L601 returns now 20m etc...

**To Reproduce**
run satromo_processor with  dev_config.py based on https://github.com/swisstopo/topo-satromo/commit/3bc2db082c01c270a963cd7a6d35eb4f2d2839f6

**Expected behavior**
adapt either the asset generation so we have selected bands 20m 10m in one image or
adapted https://github.com/swisstopo/topo-satromo/blob/step0/satromo_processor.py#L561 function  so we can pass the multiband_export https://github.com/swisstopo/topo-satromo/blob/011d4356d3fa2f7753cef38fa4968e6c92559601/satromo_processor.py#L635 for the item with 20m or 10m respectively

**OS, python version**
 -py

**Comment by gilliM** [comment]
I'm not sure what needs to be done here.
Do you want the same product but at 20m instead of 10m, or do you want the other bands available at 20m (B5, B6, B7, B8a, B11, B12)

**Comment by davidoesch** [comment]
When stated in the configuration that we want to export 10m and  some of the 20m bands of the same product the export fails. I assume that the assets need to be accessed in a different way--- am I correct?
This would need some adaption of the code above

**Comment by gilliM** [comment]
I don't see how the products should be exported according the the dev_config cited above: https://github.com/swisstopo/topo-satromo/commit/3bc2db082c01c270a963cd7a6d35eb4f2d2839f6 

If we want the bands B2, B3, B4, B8 exported at 20m, in addition to the 10m product, we need a new configuration block + a block in the __main__ of satromo_processor.py. As it's written now, we also need to create a export functions are the existing function rely directory on the configuration dictionary. For example, the function process_S2_LEVEL_1C use the dictionary config.PRODUCT_S2_LEVEL_1C within the function. 
If we don't want to add new function, we could change the code to be more flexible, but also more complex.

If you want to do something else than exporting B2, B3, B4, B8 at 20m, try to give me an example.

**Comment by gilliM** [comment]
Btw i'm happy to implement myself any necessary change. I just try to figure out what's the exact need.

**Comment by davidoesch** [comment]
We will have the  similar case with Landsat / Modis :

Export of bands with different resolution

Currently the assets do only contain 10m bands- e.g.

projects/geetest-386915/assets/col_s2_sr/S2-L2A_Mosaic_2023-06-05_T10-16-01_Bands-10m

question A) is : 

can we store in the same asset as well different spatial resolution? Does that make sense or does it make more sense to add a second asset?

Question 2: in the config we can deal with different spat resolution see eg  
   "spatial_scale_export_qa60": 60,  # Meters

Which can then be used 

Question 3:

Once 20m bands are available based on question 1) it is just a new block in https://github.com/swisstopo/topo-satromo/blob/ad22508b6ce1cd21943695aeb4fd1ec512aa6cdf/satromo_processor.py#L634 

For the bands : since we need to calculate NDMI = (B8A – B11) / (B8A + B11) we need band 11 at least

**Comment by davidoesch** [comment]
Question A and 2) "can we store in the same asset as well different spatial resolution? Does that make sense or does it make more sense to add a second asset?" :is solved:
I export now  8A and B11 channels see https://github.com/swisstopo/topo-satromo/blob/33711a8269dd15a28174594c6a1a2fda2437d336/step0_processors/step0_processor_s2_sr.py#L465 

Result: assets
projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS/S2-L2A_Mosaic_2023-10-24T104019_bands-20m 

and of course 

the 10m
projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS/S2-L2A_mosaic_2023-10-24T104019_bands-10m 


All I have to do now is 
[topo-satromo/satromo_processor.py](https://github.com/swisstopo/topo-satromo/blob/ad22508b6ce1cd21943695aeb4fd1ec512aa6cdf/satromo_processor.py#L634)

Line 634 in [ad22508](https://github.com/swisstopo/topo-satromo/commit/ad22508b6ce1cd21943695aeb4fd1ec512aa6cdf)

Add an export switch.
Seems like I need now to change the code it detects bands-20m  and bands-10m 
in
https://github.com/swisstopo/topo-satromo/blob/ad22508b6ce1cd21943695aeb4fd1ec512aa6cdf/satromo_processor.py#L578

agree?

**Comment by davidoesch** [comment]
Will test the " personal asset 10m + personal asset 20m are both available when we generate the product" approach

**Comment by davidoesch** [comment]
added for S2_SR the export https://github.com/swisstopo/topo-satromo/commit/3a0334bae3429f7303edc19365e8179a948270e2

**Comment by davidoesch** [comment]
as discussed on the 15.1. meeting --- no further action neeeded
