### ISSUE TITLE
Cloud shadows not fully masked for Landsat

### ISSUE THREAD

**Issue by Tschoun** [swisstopo/topo-satromo#37]
**Describe the bug**
The cloud / cloud shadow mask for L89 SR does not fully capture the cloud shadows. 

**To Reproduce**
1. Go to 'users/wulf/koreg-shadow/Deliverables/Landsat/L89_sr_singleDay_v01'
2. end_date '2023-07-11'
3. ROI around '46.69093, 7.23313'
4. Comparison of the layers 'L89 original' and 'L89 export'

**Expected behavior**
A mask containing all of the cloud shadows.

**Screenshots**
![image](https://github.com/swisstopo/topo-satromo/assets/44976289/00b06726-9c63-45c4-8636-061127dd0cc7)

**Additional context**
The same problem occurs for the 'users/wulf/koreg-shadow/Deliverables/Landsat/L57_sr_singleDay_v01' script with the end date '2002-07-09' for the same region and layers.

**Comment by HendrikWulf** [comment]
Hi Joan. Happy new year!
Just to clarify, you are puzzled that the mask does not contain all the cloud shadows visible in the image, right? Most cloud shadows are captured by the mask.
With Landsat I relied on fmask, which already contains a cloud shadow mask (as for the clouds). This is a different route as with S2, where we used the dark pixel approach and shadow direction projection.
Are you saying the Fmask cloud shadow detection is not good enough?

**Comment by Tschoun** [comment]
Yes, that's exactely what I meant. Is it feasible to use dark pixels and shadow direction projection for Landsat too? The remaining shadows are quite prominent and I prefer higher omission errors to commission errors.

**Comment by HendrikWulf** [comment]
Yes, implementing that should be feasible.

**Comment by HendrikWulf** [comment]
Done

**Comment by davidoesch** [comment]
15.01.2024: 
- shoudl be ready 
- we mask more pixel
- Same approach as with S2, quite strict
