### ISSUE TITLE
Set SPACE REFERENCE AOI Assets

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#39]
**Is your feature request related to a problem? Please describe.**
currently in step0_processor_s2_sr.py  (https://github.com/swisstopo/topo-satromo/blob/step0/step0_processors/step0_processor_s2_sr.py) and all step0_processor_<>_<>.py SPACE REFERENCE AOI Assets are not in swisstopo owned  GEE Account

**Describe the solution you'd like**
upload the SPACE REFERENCE AOI assets to NPOC account

- [x] aoi_CH
- [x] aoi_CH_simplified 
- [x]  S2_gri
- [x] DEM_sa3d
- [x] lakes
- [x] rivers
- [x] replace in JS and py code

(search for all users/wulf/SATROMO/  locations)

**Comment by davidoesch** [comment]
missing:

copy

- [ ] s2 TOA
- [ ] s2 SR

to PROD
/ users/satromo/prod/step0/Sentinel-2

and replace
" users/wulf/SATROMO/"
with
"projects/satromo-prod/assets/res/"

**Comment by Tschoun** [comment]
Sentinel-2 scripts also updated for both python and JavaScript
