### ISSUE TITLE
use YAML for configuration

### ISSUE THREAD

**Issue by gilliM** [swisstopo/topo-satromo#4]
I would propose to use a yaml file for the configuration.
Using a python script is kind of a mix between a configuration file and a standard script.
For example an instruction os.path.join does not belong to a configuration file.

yaml is typically used with the pyyaml library.

I would also propose to have a mecanism that select a default configuration file based on the current user, so we can have each a dev configuration file that is shared in the repository.

**Comment by davidoesch** [comment]
yaml can be pain as well.  :-) lets add this to te refactor process
