### ISSUE TITLE
Cloud mask: 80%  does not work

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#41]
**Describe the bug**
Cloud image threshold 20 m bands does  not work

**To Reproduce**
1. setting 20%  thershold for clouds  https://github.com/swisstopo/topo-satromo/blob/127e5b341c1e7af5ee69d61f4f57132c22dd48dc/step0_processors/step0_processor_s2_sr.py#L367 
2. run the 2023-10-29 for asset export for 

3. results in a processed image
-  projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS/S2-L2A_Mosaic_2023-10-29T104141_bands-20m
-  projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS/S2-L2A_Mosaic_2023-10-29T104141_bands-10m

**Expected behavior**
This image  has way more clouds than 80% and it needs to get not processed

**Screenshots**
![image](https://github.com/swisstopo/topo-satromo/assets/4577727/c57bb522-fe00-4e79-8503-dd888b69f2df)

**OS, python version**
 - current step0 branch

**Comment by gilliM** [comment]
@HendrikWulf When I removed the cloud masking, to export the cloud, it actually breaks the statistic of the number of cloud pixel in the image.
Does you see a way to keep track of the cloudy pixel while keeping the .updateMask(cloudAndCloudShadowMask.Not())  line commented ?
Maybe the right way is to used the mask layers in addMaskedPixelCount instead of relying on unmasked pixels.

**Comment by HendrikWulf** [comment]
I don't really get the intention here. Why should we "removed the cloud masking, to export the cloud" ?
Conceptually it makes a lot of sense to distinguish valid and masked pixels. Clouds are just one (though the most important) reason to mask pixel.
@gilliM Feel free to call me, if it helps.
@davidoesch Related to the cloud image. It will depend on the cloud probability threshold, which parts get masked or not. Some of the grey area may sill be cloud free - hard to tell from the image only.

**Comment by davidoesch** [comment]
@HendrikWulf @gilliM : the cloud cover percentage should adressing the cloud cover inside the simplifeid boundaries of switzerland

**Comment by HendrikWulf** [comment]
@davidoesch Yes. This is the statistic we are calculating: Percentage of valid and masked data of the image inside Switzerland (geometry: image.geometry().intersection(aoi_CH_simplified)).

**Comment by gilliM** [comment]
@HendrikWulf we want to export also cloudy pixels in the so called raw assets. We cannot just mask them.

**Comment by HendrikWulf** [comment]
okay. I get your point. In that case the most effective way is to calculate the data/cloud stats on the cloudMask.

**Comment by gilliM** [comment]
The python part for S2 SR+TOA, which might be more urgent, is done in this PR https://github.com/swisstopo/topo-satromo/pull/46
We still have adapt the javascript files.

**Comment by davidoesch** [comment]
fxied for PY in https://github.com/swisstopo/topo-satromo/pull/46

**Comment by HendrikWulf** [comment]
As requested, I implemented now the new addMaskedPixelCount function now for all sensors in JavaScript. 
Be aware that the naming of the function (add*Masked*PixelCount) and properties ('percent*Masked*') is now misleading, as we are not counting masked pixels anymore. Be also aware of the dependencies to the cloudMasking and terrainShadowDetection switches being set to 'true', as these bands form now the new basis for the percentData stat.
