### ISSUE TITLE
completed_ task status not written when exporting multpile asset to GEE

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#42]
**Describe the bug**
When creating non existing assets  of _20m and _10m band, the  completed_tasks.csv contains only  the result for _20m

**To Reproduce**
1. Run an export for the current step0 branch for an asset which is not yet in a custom colelction
2. wait till assets are completed
3.  open completed_tasks.csv
4. the completed_tasks.csv  file contains only the _20m band info like COMPLETED,COL_S2_SR_HARMONIZED_SWISS_2023-10-25,1703064618460,1703065116336,1703064623146,EXPORT_IMAGE,['https://code.earthengine.google.com/?asset=projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS/S2-L2A_Mosaic_2023-10-25T101029_bands-20m'],1,3274.73974609375,EA27FZTU4GOWMSIWJEK7NS37,projects/earthengine-legacy/operations/EA27FZTU4GOWMSIWJEK7NS37

**Expected behavior**
the completed_tasks.csv  file contains 
-  the _20m band info like COMPLETED,COL_S2_SR_HARMONIZED_SWISS_2023-10-25,1703064618460,1703065116336,1703064623146,EXPORT_IMAGE,['https://code.earthengine.google.com/?asset=projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS/S2-L2A_Mosaic_2023-10-25T101029_bands-20m'],1,3274.73974609375,EA27FZTU4GOWMSIWJEK7NS37,projects/earthengine-legacy/operations/EA27FZTU4GOWMSIWJEK7NS37.

and the _10m_ band
- .....['https://code.earthengine.google.com/?asset=projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS/S2-L2A_Mosaic_2023-10-25T101029_bands-10m'],

**OS, python version**
 - PY

**Additional context**
I assume you need to add a similar approach as in https://github.com/swisstopo/topo-satromo/blob/127e5b341c1e7af5ee69d61f4f57132c22dd48dc/satromo_processor.py#L623 
when creating completed_tasks.csv  for  assets whcih are generated on the same day...

**Comment by gilliM** [comment]
I'm looking into that. It's not exactly simple, as we decided that we wanted to have one product = one asset. There is many logical points that are not valid anymore.

**Comment by davidoesch** [comment]
Thanks 
In any case : if u reach a point of where u think it gets to complex let me know

**Comment by davidoesch** [comment]
fixed with https://github.com/swisstopo/topo-satromo/pull/44
