### ISSUE TITLE
use a proper logging library

### ISSUE THREAD

**Issue by gilliM** [swisstopo/topo-satromo#5]
I would refrain to use any print instruction in any script. 
I propose to use the [loguru](https://pypi.org/project/loguru/) library for logging. This library is close to the standard library, but implements some useful gadgets (color in logging for example) that is not always easy to setup correctly.

I then would propose to add multiple handlers, such as a stream handler, a log file handler and maybe to combine it with notifier, to get a message when a problem occur.
see: notifier[](https://loguru.readthedocs.io/en/stable/overview.html#exhaustive-notifier)

**Comment by davidoesch** [comment]
logging and exception handling (Try ... except ) are both not yet implemented,and printing is just for the moment and for debugging easily, [loguru](https://pypi.org/project/loguru/) library looks really nice ( the standard logging module can be a pain)
