### ISSUE TITLE
Add CLOUDmask type and percentage orbit to metadata

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#54]
**Is your feature request related to a problem? Please describe.**
Since we are using either cloudscore+ or s2cloudless  we need store this information and the  percentage of the total orbit

**Describe the solution you'd like**
add on export to asset as properties to asset in

- [x] step0_processor_s2_sr.py
- [x] step0_processor_s2_toa.py

so that we have in the metdata,json in "CLOUDPROBABILITY-10M": "PROPERTIES": 

- [x] path to asset used for cloudmask (either cloudscore+ or s2cloudles)
- [x] percentage cloud the percentData value as in https://github.com/swisstopo/topo-satromo/blob/510dd4d51141d22ff81bae2fc6795575a9b41c2c/step0_processors/step0_processor_s2_sr.py#L375

**Describe alternatives you've considered**

**Additional context**

**Comment by Tschoun** [comment]
Added the properties for the cloud detection algorithm:
- S2_SR -> 8cae8afdb79ed3477b7c15d68862aaef42e7034c
- S2_TOA -> 1f7a9eda1476cd4d5cd253755b421600fb20089e

The assets now have the properties:
- "cloud_detection_algorithm" -> Options: CloudScore+ or s2cloudless
- "cloud_mask_threshold" -> numerical value(s)

Is direct path to cloud asset needed? There's also no direct path to the S2 dataset itself...
And is the distinction between "percent_masked" and "percent_masked_clouds" needed?

**Comment by davidoesch** [comment]
Imho: 
-percent_masked is enough
- direct path to cloud asset not needed

**Comment by Tschoun** [comment]
Then this issue is complete
