### ISSUE TITLE
Link fullres: remove tiny url

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#57]
**Is your feature request related to a problem? Please describe.**
in https://github.com/swisstopo/topo-satromo/blob/db0fb783d88f491cf67bb63e6e642a3bf8ed4fba/satromo_publish_stac_fsdi.py#L182
we use tinyurl to reduce the length of url for the part for the preview website.
due to the fact that l<links> in geoadmin stac are limited to a length of 200

**Describe the solution you'd like**
after geoadmin stac is pacthed with at least 1024 length for links, we replace
'https://tinyurl.com/sat54'
with

'https://cms.geo.admin.ch/Topo/umweltbeobachtung/satromocogviewer.html'

**Additional context**
swisstopo cogis informed via  Pasquale Di Donato

**Comment by mariokeusen** [comment]
opened a task for service stac BGDI: internal https://jira.swisstopo.ch/browse/PB-340

**Comment by davidoesch** [comment]
tested with https://sys-data.int.bgdi.ch/#/collections/ch.swisstopo.swisseo_s2-sr_v100/items/2024-03-07t103911
