### ISSUE TITLE
Cloud parameter does not work

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#58]
**Describe the bug**
Cloud threshold settings  do not work properly

**To Reproduce**
We get 

For 90 % setting https://github.com/swisstopo/topo-satromo/blob/46086d429040a7cbb82ba4f34f0ea148c8aa18bf/step0_processors/step0_processor_s2_sr.py#L374

We get 59.3% "percentMasked" (https://sys-data.int.bgdi.ch/ch.swisstopo.swisseo_s2-sr_v100/2024-02-23t103031/ch.swisstopo.swisseo_s2-sr_v100_mosaic_2024-02-23t103031_metadata.json)
![image](https://github.com/swisstopo/topo-satromo/assets/44976289/28f8d406-9e6f-4ed7-a29e-29519b72f916)

This
„Cutting asset create for projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS / 2024-02-23
Reason: cloudy
Asset not yet available for date 2024-02-23“
Image is actually pretty cloudfree

 this pretty cloudfree scene

<img width="375" alt="image" src="https://github.com/swisstopo/topo-satromo/assets/4577727/216eb0d3-c4f2-486b-bb02-15eb7b8e0b0a">

**Expected behavior**
Scene is recognized as not cloudy: Threshold for % cloudiness does take the "percentMasked" value into account.

**Screenshots**

**OS, python version**
 -

**Additional context**

**Comment by davidoesch** [comment]
when we we switch to "20" in S2_sr = S2_sr.filter(ee.Filter.gte('percentData', 10)) in https://github.com/swisstopo/topo-satromo/blob/46086d429040a7cbb82ba4f34f0ea148c8aa18bf/step0_processors/step0_processor_s2_sr.py#L374

 Then the scene is not cloudy

**Comment by gilliM** [comment]
After an analysis, i also find that percent of clear data on the scene is 40.7, which is completely reasonable.
There is no problem here for me.

**Comment by davidoesch** [comment]
It seems that not all S2 tiles of the orbit were available in GEE at the time of generation.  There was cloudiness in the available tiles.
To overcome this, we will introduce a delayed processing and a  check if the orbit is complete https://github.com/swisstopo/topo-satromo/issues/61.

What would be good in this case to see the actual amount of pixel  to extent https://github.com/swisstopo/topo-satromo/blob/af33a72b154535fe4ec8b7ca05288adb0e5398ea/step0_processors/step0_processor_s2_sr.py#L375

with something in this direction
```
# Calculate the total number of pixels in the original collection
total_pixels_original = S2_sr.reduce(ee.Reducer.sum()).select([0], ['total_pixels'])

# Calculate the total number of non-cloudy pixels in the original collection
non_cloudy_pixels_original = S2_sr.map(lambda img: img.updateMask(img.select('QA60').eq(0))).reduce(ee.Reducer.sum()).select([0], ['non_cloudy_pixels'])

# Calculate the percentage of cloud-free pixels
percentage_cloud_free_original = ee.Number(non_cloudy_pixels_original).divide(total_pixels_original).multiply(100).getInfo()

print("Percentage of cloud-free pixels in the original images:", percentage_cloud_free_original)
```

But I don't get the total number of non-cloudy pixels in the original collection --- @gilliM any ideas for a code snippet here?
