### ISSUE TITLE
Check for complete orbit tiles

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#61]
We need to know if all tiles of a spefici orbit are available: reason 

- S2 GEEE Asset processing is encountering a delay,  only partial orbit tiles are available

**Describe the solution you'd like**
we know the toteal number of tiles we need for each orbit number. so we can check the orbit number of the first tile we ingest and then look up the total nu,bers of tiles we should have. if this number is met: we can start the ingestion

**Describe alternatives you've considered**
Just delay the realtime ingestion by 24-48 hours

**Additional context**
see https://github.com/swisstopo/topo-satromo/issues/58

**Comment by Tschoun** [comment]
Abortion of processing added to both S2_SR and S2_TOA. No processing of the data if the there are not yet all tiles to complete the overpass.
