### ISSUE TITLE
l57 ASSET export AOI not taken into account

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#64]
**Describe the bug**
l57 export to asset does not export the full aoi_exp 

**To Reproduce**
1. using https://github.com/swisstopo/topo-satromo/blob/dev/step0_processors/step0_processor_l57_sr.py  as base as dfined in https://github.com/swisstopo/topo-satromo/tree/cd42cc893f118f72b1114760f60a41b445ed3b1e
2. run date "2020-11-07" with the dev_config
4. See exported result in projects/satromo-int/assets/COL_LANDSAT_SR_SWISS

**Expected behavior**
 Full mosaic is as asset in projects/satromo-int/assets/COL_LANDSAT_SR_SWISS  as in the JS https://code.earthengine.google.com/f70a67366ee74ff46b75445b39e07a71

**Comment by gilliM** [comment]
![image](https://github.com/swisstopo/topo-satromo/assets/6716422/9739037d-e5af-4374-b27e-b5d802042569)

I get the same output from the javascript - export to drive - and the python - export to asset for the date 2020-11-07.

**Comment by davidoesch** [comment]
I rerun it again today, now the asset export is working as expected ( yesterday I exported three times as asset, always an issue)

root cause: GEE

![image](https://github.com/swisstopo/topo-satromo/assets/4577727/169f42b4-150c-40db-98eb-a5865cdfe6b2)
