### ISSUE TITLE
l57 ASSET empty Data for Landsat5

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#65]
**Describe the bug**
l57 export to asset does not export data for L5

**To Reproduce**
1. using https://github.com/swisstopo/topo-satromo/blob/a7b3bf19098ea6cf83d991d43cbd93ac18b80469/step0_processors/step0_processor_l57_sr.py  as base as defined in https://github.com/swisstopo/topo-satromo/tree/cd42cc893f118f72b1114760f60a41b445ed3b1e
2. run date "1998-10-20" with the dev_config
4. See exported result in projects/satromo-int/assets/COL_LANDSAT_SR_SWISS : empty  dataset for 1998-10-20

**Expected behavior**
 Full mosaic is as asset in projects/satromo-int/assets/COL_LANDSAT_SR_SWISS  as in the JS https://code.earthengine.google.com/f70a67366ee74ff46b75445b39e07a71 for 1998-10-20

**Comment by gilliM** [comment]
The linked JS script has still the date 2020 in it. Do you have an exact copy of the JS version that you executed ?

**Comment by gilliM** [comment]
I've no problem to get the image for 1998-10-20 with your code, in javascript or with the python code.
I also see a date for 2020 in the python code linked above.
I would need to get the exact code that you execute to look further.

**Comment by davidoesch** [comment]
Here as well as in #64 : today the export works. tried on 13.03 3 times, no error thrown by GEE but created empty assets
root cause: by GEE
![image](https://github.com/swisstopo/topo-satromo/assets/4577727/194ab802-0be3-4ccf-a37b-a0e41fc05190)

thanks @gilliM for the patience
