### ISSUE TITLE
Add SOURCE in properties

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#67]
Below

 https://github.com/swisstopo/topo-satromo/blob/0471b9c87d53164295be3efdb222fe05ee230cb2/step0_processors/step0_processor_s2_sr.py#L430

add 
.set('DATA_SOURCE', "Contains modified Copernicus Sentinel data [Year]") \

**Comment by davidoesch** [comment]
fixed with https://github.com/swisstopo/topo-satromo/commit/3a32ff065514502903067537839138d2d430474a

**Comment by davidoesch** [comment]
not yet fixed to be tested

**Comment by Tschoun** [comment]
#67 is fixed, newly computed assets contain the property DATA_SOURCE "Contains modified Copernicus Sentinel data YYYY"
