### ISSUE TITLE
Masks for vegetation/lowervegetation/forest for Liechtenstein missing

### ISSUE THREAD

**Issue by Tschoun** [swisstopo/topo-satromo#69]
**Describe the bug**
The masks for vegetation, lower vegetation and forest don't contain Liechtenstein. This is due to the country missing in the habitat map for Switzerland which was used for the generation of the masks.

**Expected behavior**
Masks covering Switzerland and Liechtenstein.

**Possible short-term solutions**
CLC+Backbone (M:\Appl\DATA\PROD\topo\tbk\tbkn\npoc\Umweltbeobachtung\Trockenheitsmonitoring\Dateien\CLCplusBackbone)
- Forest: classes 2-4
- Vegetation: classes 2-8

**Screenshots**
![image](https://github.com/swisstopo/topo-satromo/assets/44976289/0991630d-d167-46d3-bd25-0f12eb66e356)

**Comment by davidoesch** [comment]
Alterntaive: CLC+Backbone : 10m resolution https://land.copernicus.eu/en/products/clc-backbone  ( Siehe auch INfo in Geomatik Schweiz 3-4 / 2024)

**Comment by Tschoun** [comment]
Fixed with the [CLC+BAckbone 2018](https://doi.org/10.2909/cd534ebf-f553-42f0-9ac1-62c1dc36d32c) dataset. 
- Forest: classes 2-4
- Lower vegetation: classes 5-8
- Vegetation: classes 2-8

Extended the existing masks for Switzerland derived from the habitat map with the masks for Liechtenstein derived from the CLC+ Backbone dataset. The assets on the GEE prod environment were exchanged and the descriptions updated.
