### ISSUE TITLE
refactoring global variables and functions

### ISSUE THREAD

**Issue by gilliM** [swisstopo/topo-satromo#7]
In an early step, i propose to refactor and use more a class/method architecture rather than functions.
Also, i would refrain to use any global variable, without exception.

The library simple-settings is useful to ship a bunch of variables between the scripts, though limited to a single thread (but it's very certainly ok here).

**Comment by davidoesch** [comment]
Agree, a refactor makes sense the current state is WorkInProgress to see if we are able to run it on GH and get an estimate of the transfer rate. keep in mind that the code should be understandable as well for  rookies /noobs.
