### ISSUE TITLE
asset CloudProbability  not uint8

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#73]
**Describe the bug**
with CS+ cloud score is not uint8 but double with v0.0.1

**To Reproduce**
projects/satromo-prod/assets/col/S2_SR_HARMONIZED_SWISS/S2-L2A_mosaic_2023-08-20T103631_bands-10m
<html>
<body>

9 | cloudProbability | double
-- | -- | --

</body>
</html>

**Expected behavior**
as in projects/satromo-prod/assets/col/S2_SR_HARMONIZED_SWISS/S2-L2A_mosaic_2024-03-14T102811_bands-10m
<html>
<body>

9 | cloudProbability | unsigned int8
-- | -- | --

</body>
</html>

**Screenshots**
expected  result
![image](https://github.com/swisstopo/topo-satromo/assets/4577727/daf2815a-228c-431b-83fe-e4e70a75fdea)

**OS, python version**
 -v0.0.1

**Additional context**

cs+ needs to be casted to uint8 before exporting

needs a fix for

- [x] python s2_sr
- [ ] python s2_toa
- [x] JS s2_sr 
- [x] JS s2_toa

**Comment by davidoesch** [comment]
fixed eg in projects/satromo-int/assets/COL_S2_SR_HARMONIZED_SWISS/S2-L2A_mosaic_2020-07-11T103629_bands-10m

**Comment by Tschoun** [comment]
will do the JavaScript code

**Comment by Tschoun** [comment]
Fixed the data type for S2_TOA here: f37d71b42317150b50e9458a1b0f202c39dde4e3
Will be merged to the main branch with the next merge.
Java Script fixed in prod environment.

**Comment by davidoesch** [comment]
fixed existing data on PRD with https://github.com/swisstopo/topo-satromo/blob/dev/main_functions/util_castassetbands.py
