### ISSUE TITLE
google-drive utility

### ISSUE THREAD

**Issue by gilliM** [swisstopo/topo-satromo#8]
Having some a utility class to manage the google-drive state specifically for our usage would be clean.

For example, this class would manage the authentication to google drive, the deletion of files, the listings, etc. 
On the long run, will certainly have different scripts for example for different satellites. We could reuse the same functions to manage the files on the drive in the different scripts. It would therefore be useful to externalize these function in a module and make as generic as possible.

**Comment by davidoesch** [comment]
currently the https://github.com/swisstopo/topo-satromo/blob/main/processing/running_tasks.csv contains the information in a csv for each export and the corresponding files are derived, accessed and on successful move deleted

to have here a generic module to move files makes sense. Keep in mind that space is limited on GH free tier so best is to use rclone to move files between gdrive and s3 without actaully storing it on GH. merging files wirks best with gdalwarp with *VSIL_CURL_* paramters. but this works only for read , not for wrting COG tiff on s3 , see https://www.getbounds.com/blog/generating-cloud-optimized-geotiffs-and-raster-tiles-with-gdal/ TIFF writing requires random writing capabilities and /vsis3/ supports only sequential writing. Consequently you need to create a local copy before uploading it https://github.com/OSGeo/gdal/issues/1189
