### ISSUE TITLE
Rerun if "Tile upload incomplete " and "Cloud probability data missing"

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#82]
**Is your feature request related to a problem? Please describe.**
empty_asset_list can contain "Tile upload incomplete " and "Cloud probability data missing". So if we rerun a specific date, we need to check that the missing clouds and tiles are still not available

**Describe the solution you'd like**
 if not in the available asset list ,check if in empty_asset_list as in https://github.com/swisstopo/topo-satromo/blob/9ed1b93fc1c6c804ab83a1dc254edea4b7bf9409/step0_functions.py#L91 then try to rerun it if "Tile upload incomplete " and "Cloud probability data missing" and if successful remove  it from empty_asset_list

**Describe alternatives you've considered**
delete manually available asset list and then rerun

**Comment by Tschoun** [comment]
Fixed with https://github.com/swisstopo/topo-satromo/commit/2da69eb6edfedc83802b7265cb926d98140155d2
-> run with command promt
