### ISSUE TITLE
usable with personal account for dev ?

### ISSUE THREAD

**Issue by gilliM** [swisstopo/topo-satromo#9]
I haven't checked if it was possible or really useful, but i've the feeling that for development, the use of a personal google account instead of a service account would be useful to manage the files on google drive and the tasks on earth engine.
What do you think about enabling the use of personal account on the top of the service account ?

**Comment by davidoesch** [comment]
AFAIK: you can not run GEE with a personal account directly . You need a service account , which is linked to your  personal account. This is how I understood it based on the links in https://github.com/swisstopo/topo-satromo#installation : GoogleEarthEngine credentials: the GEE json keyfile.json according to your [Google Service Account](https://developers.google.com/earth-engine/guides/service_account) and a private key for the [service account](https://developers.google.com/earth-engine/guides/service_account#create-a-private-key-for-the-service-account). Ensure that service account has the [Earth Engine API enabled](https://developers.google.com/earth-engine/cloud/earthengine_cloud_project_setup) and has been has been [registered](https://code.earthengine.google.com/register) for use with Earth Engine. Then you also need to activate your GoogleDrive / Google developers console API activation for your ServiceAccount Project https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project= to access GDRIVE via API
