### ISSUE TITLE
Oversaturated pixel / overcorrected  SR

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#97]
### **Description**

The S2-SR dataset shows overcorrected surface reflectance (SR) values due to Sen2Cor processing and the absence of BRDF correction in Copernicus data. This results in extreme NDVI values, which in turn affects the VHI calculation.

The affected areas correspond to those classified as "Topographic casted shadows" (previously labeled "Dark features/Shadows" for data before 2022-01-25) in the SCL mask. More details can be found in the Sentinel-2 scene classification documentation: https://custom-scripts.sentinel-hub.com/custom-scripts/sentinel-2/scene-classification/.

### **To Reproduce**

1. Surface Reflectance (S2 SR) layer: [Link to S2 SR](https://s.geo.admin.ch/zovtbpv8vbxd)
2. Vegetation Health Index (VHI) layer: [Link to VHI](https://s.geo.admin.ch/ca3qkslncopn)

The issue arises because the topographically casted shadow areas are not properly accounted for in atmospheric correction, leading to inaccurate SR values.

See also: [Google Earth Engine Script](https://code.earthengine.google.com/d721a64f277c897f9dd4997da01dd869).

### **Expected Behavior**

Evaluate the Scene Classification Layer (SCL) information mask using the Google Earth Engine script linked above, and apply the following improvements based on the classification:

- [ ] Add to the mask layer in S2 SR the values 0, 1, 2, and 3 (SCL categories). To be determined if these should be used for classification or added as a byte mask.
- [ ] Apply the mask to VHI: Invalid pixels in the SCL categories should be excluded from VHI calculations.

**Screenshots**
![{AD0125F1-9FFB-4BFE-B2B4-5E6667F8ACB3}](https://github.com/user-attachments/assets/3af30b38-009a-4eb8-b683-1a8fbbdd1b14)

![{7C30DA2F-10E2-4FD5-BC3D-19FE486EE176}](https://github.com/user-attachments/assets/ea0d04ee-96bd-4610-a029-a72fe98b3b4c)

![{4D47AC59-60EA-4F96-AD7F-7DEA04CF5D61}](https://github.com/user-attachments/assets/b4be9aeb-98cd-436d-a175-839cc5d041b5)

### **Additional Context**

- [ ] Additionally, include a snow mask (SCL value 11). For these pixels, no VHI should be calculated.

**Comment by davidoesch** [comment]
looks like the challenge is in sen2core:

The basis for the topography correction is the determination of the illumination conditions (cos beta) using DEM (Aspect, Slope) and sun (Azimuth, Zenith). With very “poor” illumination conditions, certain algorithms can lead to overcorrection, for example with the Lambertian Method (used in Sentinel-2 Sen2cor processing for Level 2A data):

![image](https://github.com/user-attachments/assets/cc149543-5efd-4476-9494-20d7bb06255a)

where g_h is the reflectance after correction, g_t is the reflectance before correction, theta_s is the slope and beta is the illumination angle. If the illumination angle becomes very flat (beta ~ 90°, i.e. hardly any illumination), the denominator in the fraction is almost 0, which means that g_t is multiplied by a very large number, resulting in a very high (over-corrected) reflectance g_h.


Next step: create an illumination mask and adapt a mask to account for  values where cos beta is close to 0

**Comment by Tschoun** [comment]
A real fix of this problem is only feasible by replacing the atmospheric correction performed in sen2cor with an atmospheric correction specifically tailored for Switzerland (higher focus on hilly and mountainous terrain). 
So far the solution is to include the illumination angle of each pixel in the 'terrainShadowMask' band as values from 0-90°. The previous terrain shadow mask is added to the same band as the value 100. The user is thus free to use this band to either:

1. mask non-illuminated pixels only `image.updateMask(image.select('cloudAndCloudShadowMask').lt(100))`
2. or mask also pixels with insufficient illumination (less light illuminating a pixel the higher the illumination angle) with e.g. `image.updateMask(image.select('cloudAndCloudShadowMask').lt(65))`
